/**
 * Reference-led electric-blue veterinary UI: a giant typographic stage, pet cutouts, and sculptural white information panels.
 */
import { Link } from "wouter";
import { ArrowUpRight, PawPrint, Sparkles } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PageMeta } from "@/components/PageMeta";
import { assets, faqs, services } from "@/lib/clinic-content";

export default function Home() {
  return <main className="neo-main">
    <PageMeta title="Paws+Pine Veterinary Clinic — Fictional Tier 1 Demo" description="A fictional three-page veterinary clinic demo with a high-contrast pet-first interface and non-live visit request form." />
    <section className="neo-hero"><div className="neo-title-stage"><span className="neo-title-kicker"><PawPrint size={15} /> Fictional veterinary clinic</span><h1>Paws+Pine <span>Clinic</span></h1><div className="hero-chip chip-left"><strong>03</strong><span>fixed public<br />demo pages</span></div><div className="hero-chip chip-right"><span>Pet care communication<br />built around clear next steps.</span><Link href="/services" className="lime-link">Explore services <ArrowUpRight size={15} /></Link></div></div><div className="neo-pet-stage"><img src={assets.heroPets} alt="Fictional cocker spaniel and silver cat for the Paws and Pine veterinary clinic demo" /><div className="pet-stage-note"><span>Care conversations</span><strong>made<br />clearer.</strong></div><Link href="/request" className="hero-visit-cta">Request a visit <ArrowUpRight size={17} /></Link></div></section>

    <section className="neo-about-shell"><div className="neo-about-card"><div className="about-title">About<br />the demo</div><img className="about-pup" src={assets.aboutPup} alt="Fictional cream dog in a lime green sweater" /><div className="about-copy"><p className="about-statement"><em>Clinic-ready clarity</em> meets a visual system designed for a future client’s real, approved information. Nothing here promises availability, a treatment, or a booking.</p><div className="about-metrics"><div><strong>03</strong><span>fixed public pages</span></div><div><strong>06</strong><span>sample care paths</span></div><div><strong>0</strong><span>real data submitted</span></div></div></div></div></section>

    <section className="neo-services-section"><div className="neo-services-heading"><div><span className="neo-overline"><Sparkles size={14} /> Built for Tier 1</span><h2>Our care <em>paths.</em></h2></div><div><p>Six concise service examples show how a focused clinic website can keep essential information easy to scan.</p><Link href="/services" className="lime-link">See all services <ArrowUpRight size={15} /></Link></div></div><div className="neo-service-strip"><article className="neo-service-card intro-card"><span>01.</span><h3>{services[0].title}</h3><p>{services[0].short}</p><Link href="/services" aria-label="Explore wellness visits"><ArrowUpRight size={18} /></Link></article><article className="neo-service-card photo-card"><div className="photo-card-label">Clinic service moment</div><img src={assets.serviceExam} alt="Fictional dog receiving a veterinary exam" /><h3>Safe, clear, and thoughtfully explained.</h3><p>Sample imagery is art-directed for the demo, then replaced with approved client assets.</p></article><article className="neo-service-card number-card"><span>03.</span><h3>{services[2].title}</h3><p>{services[2].short}</p><Link href="/services" aria-label="Explore puppy and kitten care"><ArrowUpRight size={18} /></Link></article><article className="neo-service-card number-card"><span>04.</span><h3>{services[3].title}</h3><p>{services[3].short}</p><Link href="/services" aria-label="Explore senior pet check-ins"><ArrowUpRight size={18} /></Link></article></div></section>

    <section className="neo-faq-shell"><div className="neo-faq-card"><div className="faq-side"><span className="neo-overline">A few clear answers</span><h2>What this site <em>does.</em></h2><p>Optional FAQs live inside the fixed three-page architecture—never as a fourth page.</p></div><Accordion type="single" collapsible className="neo-faq-list">{faqs.map((faq, index) => <AccordionItem value={`faq-${index}`} key={faq.question}><AccordionTrigger>{faq.question}</AccordionTrigger><AccordionContent>{faq.answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section className="neo-bottom-cta"><div><span>Fictional Paws+Pine Veterinary Clinic</span><h2>Care begins with <em>one good question.</em></h2></div><div><p>See the Tier 1 request experience. It validates locally, shares no data, and never pretends to confirm an appointment.</p><Link href="/request" className="lime-cta">Open visit request <ArrowUpRight size={17} /></Link></div></section>
  </main>;
}
