import { ArrowUpRight, Clock3, MapPin, PawPrint, Phone } from "lucide-react";
import { Link } from "wouter";
import { PageMeta } from "@/components/PageMeta";
import { assets, clinic } from "@/lib/clinic-content";

function ClinicMap() {
  const locationQuery = encodeURIComponent(`${clinic.address}, ${clinic.city}`);
  return <div className="pp-location-map-card"><div className="pp-map-heading"><span>Map view</span><strong>{clinic.city}</strong></div><iframe className="pp-location-map pp-location-embed" title={`Google Maps search for ${clinic.address}, ${clinic.city}`} src={`https://www.google.com/maps?q=${locationQuery}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><div className="pp-map-fallback" aria-hidden="true"><span className="pp-map-grid" /><span className="pp-map-road pp-map-road--one" /><span className="pp-map-road pp-map-road--two" /><span className="pp-map-demo-pin"><MapPin size={24} /></span><div><span>Clinic location</span><strong>2nd Street</strong><small>{clinic.city}</small></div></div><a className="pp-map-open" href={`https://www.google.com/maps/search/?api=1&query=${locationQuery}`} target="_blank" rel="noreferrer">Open in Google Maps <ArrowUpRight size={14} /></a><div className="pp-map-caption"><span className="pp-map-pin" aria-hidden="true"><MapPin size={16} /></span><p><strong>{clinic.address}</strong><br />Google Maps search for the approved clinic address.</p></div></div>;
}

export default function Location() {
  return <main className="neo-main pp-location-page"><PageMeta title={`Location — ${clinic.name} ${clinic.descriptor}`} description={`Find ${clinic.name} at ${clinic.address}, ${clinic.city}.`} /><section className="pp-location-hero pp-reveal"><div><span className="pp-page-eyebrow"><PawPrint size={15} /> Optional location page</span><h1>Find care<br /><em>close by.</em></h1></div><div><p>Visit Paws+Pine in Calamba, Laguna for a clear, thoughtful starting point. Request a visit first and our team will follow up directly.</p></div></section><section className="pp-location-content pp-reveal"><div className="pp-location-card"><div className="pp-location-photo"><img src={assets.clinicHero} alt="Paws and Pine clinic consultation space" /></div><div className="pp-location-copy"><span className="pp-page-eyebrow">Visit Paws+Pine</span><h2>Start with<br /><em>the right place.</em></h2><div className="pp-location-facts"><div className="pp-location-fact"><MapPin size={20} /><div><span>Address</span><p>{clinic.address}<br />{clinic.city}</p></div></div><div className="pp-location-fact"><Phone size={20} /><div><span>Contact</span><p>{clinic.phone}<br />{clinic.email}</p></div></div></div><Link href="/request" className="lime-cta">Request a visit <ArrowUpRight size={17} /></Link></div></div><ClinicMap /></section><section className="pp-hours-section pp-reveal" aria-labelledby="business-hours-title"><div><span className="pp-page-eyebrow"><Clock3 size={15} /> Business hours</span><h2 id="business-hours-title">Plan your visit<br /><em>with confidence.</em></h2><p>These are Paws+Pine demonstration hours. Confirm client-approved hours before any production launch.</p></div><dl className="pp-hours-grid">{clinic.businessHours.map((entry) => <div key={entry.days}><dt>{entry.days}</dt><dd>{entry.hours}</dd></div>)}</dl></section><p className="pp-location-note">Paws+Pine is a fictional demonstration clinic. The Calamba address supplied for this demo is used in the location presentation and Google Maps destination; confirm all final client content before launch.</p></main>;
}
