import { ArrowUpRight, Clock3, Landmark, MapPin, Navigation, PawPrint, Phone } from "lucide-react";
import { Link } from "wouter";
import { PageMeta } from "@/components/PageMeta";
import { assets, clinic } from "@/lib/clinic-content";

const locationClinicName = "Paws+Pine Veterinary Clinic";
const locationAddress = "Center Stall No. 4027, 2nd Street";
const locationCity = "Calamba, Laguna";
const suppliedDirectionsEmbed = "https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d3867.7651877487674!2d121.15219677535784!3d14.20852278655503!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e9!4m5!1s0x33bd63cf0332a4d1%3A0x64e104a26340b384!2sHayop%20Kalinga%20Veterinary%20Clinic%2C%20Center%20Stall%20No%2C%204027%202nd%20Street%2C%20Calamba%2C%20Laguna!3m2!1d14.2075514!2d121.154726!4m5!1s0x33bd63ce87362e4b%3A0x7ca9e107c335fbab!2sCalamba%20Trade%20Center%2C%206554%2B3JW%2C%20JP%20Rizal%20St%2C%20Calamba%2C%204027%20Laguna!3m2!1d14.207739!2d121.156577!5e0!3m2!1sen!2sph!4v1787400409039!5m2!1sen!2sph";
const directionsUrl = "https://www.google.com/maps/dir/?api=1&origin=Center+Stall+No.+4027,+2nd+Street,+Calamba,+Laguna&destination=Calamba+Trade+Center,+JP+Rizal+Street,+Calamba,+Laguna&travelmode=driving";

function ClinicMap() {
  return <div className="pp-location-map-card pp-supplied-map"><div className="pp-map-frame"><div className="pp-map-heading"><span>Driving route</span><strong>Clinic ↔ Trade Center</strong></div><iframe className="pp-location-map pp-location-embed" title="Google Maps driving directions between Paws+Pine Veterinary Clinic and Calamba Trade Center" src={suppliedDirectionsEmbed} loading="lazy" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /><a className="pp-map-open" href={directionsUrl} target="_blank" rel="noreferrer">Open driving directions <ArrowUpRight size={14} /></a></div></div>;
}

export default function Location() {
  return <main className="neo-main pp-location-page"><PageMeta title={`Location — ${locationClinicName}`} description={`Find ${locationClinicName} at ${locationAddress}, ${locationCity}.`} /><section className="pp-location-hero pp-reveal"><div><span className="pp-page-eyebrow"><PawPrint size={15} /> Complimentary location page</span><h1>Find care<br /><em>close by.</em></h1></div><div><p>Included with this Paws+Pine demo: a clear location, map destination, and business-hours view. Request a visit first and our team will follow up directly.</p><Link href="/request" className="pp-location-hero-cta">Request a visit <ArrowUpRight size={15} /></Link></div></section><section className="pp-location-content pp-reveal"><div className="pp-location-card"><div className="pp-location-photo"><img src={assets.clinicHero} alt="Paws and Pine clinic consultation space" /></div><div className="pp-location-copy"><span className="pp-page-eyebrow">{locationClinicName}</span><h2>Start with<br /><em>the right place.</em></h2><div className="pp-location-facts"><div className="pp-location-fact"><MapPin size={20} /><div><span>Address</span><p>{locationAddress}<br />{locationCity}</p></div></div><div className="pp-location-fact"><Phone size={20} /><div><span>Contact</span><p>{clinic.phone}<br />{clinic.email}</p></div></div></div><Link href="/request" className="lime-cta">Request a visit <ArrowUpRight size={17} /></Link></div></div><ClinicMap /></section><section className="pp-directions-section pp-reveal" aria-labelledby="directions-title"><div><span className="pp-page-eyebrow"><Navigation size={15} /> Driving directions</span><h2 id="directions-title">Use the route<br /><em>you recognise.</em></h2></div><div className="pp-directions-grid"><article><Landmark size={20} /><span>Nearby landmark</span><h3>Calamba Trade Center</h3><p>The supplied Google Maps route connects {locationClinicName} with Calamba Trade Center on JP Rizal Street.</p></article><article><MapPin size={20} /><span>Clinic address</span><h3>{locationClinicName}</h3><p>{locationAddress}, {locationCity}. Use the directions button for the provided driving route.</p></article></div></section><section className="pp-hours-section pp-reveal" aria-labelledby="business-hours-title"><div><span className="pp-page-eyebrow"><Clock3 size={15} /> Business hours</span><h2 id="business-hours-title">Plan your visit<br /><em>with confidence.</em></h2><p>These are Paws+Pine demonstration hours. Confirm client-approved hours before any production launch.</p></div><dl className="pp-hours-grid">{clinic.businessHours.map((entry) => <div key={entry.days}><dt>{entry.days}</dt><dd>{entry.hours}</dd></div>)}</dl></section><p className="pp-location-note">Paws+Pine is a fictional demonstration clinic. The supplied Hayop Kalinga location, Calamba directions route, and landmark are shown as approved location reference content; confirm all final client content before launch.</p></main>;
}
