import { FormEvent, useState } from "react";
import { CheckCircle2, LoaderCircle, MessageCircleHeart, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { createSessionReview, type SessionReview } from "@/lib/sessionReview";

type ReviewErrors = Record<string, string>;
type ReviewFormProps = { onDisplayed: (review: SessionReview) => void };

export function ReviewForm({ onDisplayed }: ReviewFormProps) {
  const [rating, setRating] = useState(0); const [errors, setErrors] = useState<ReviewErrors>({}); const [submitted, setSubmitted] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false);
  function validate(form: FormData) { const next: ReviewErrors = {}; const name = String(form.get("reviewerName") || "").trim(); const email = String(form.get("reviewerEmail") || "").trim(); const feedback = String(form.get("reviewFeedback") || "").trim(); if (!name) next.name = "Please add your name."; if (!email) next.email = "Please add an email address."; else if (!/^\S+@\S+\.\S+$/.test(email)) next.email = "Please use a valid email format."; if (!rating) next.rating = "Please choose a rating."; if (!feedback) next.feedback = "Please share your review."; if (form.get("reviewConsent") !== "on") next.consent = "Please confirm you understand this review is displayed only for this browser session."; return next; }
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const next = validate(form); setErrors(next); if (Object.keys(next).length) return; setIsSubmitting(true); const review = { displayName: String(form.get("reviewerName") || "").trim(), rating, feedback: String(form.get("reviewFeedback") || "").trim() }; await new Promise((resolve) => window.setTimeout(resolve, 320)); onDisplayed(createSessionReview(review)); setIsSubmitting(false); setSubmitted(true); }
  if (submitted) return <div className="pp-review-success" role="status" aria-live="polite"><CheckCircle2 size={42} /><span className="pp-page-eyebrow">Review shown</span><h3>Thank you for<br /><em>sharing your experience.</em></h3><p>Your review is now visible in this page’s Reviews section. It is not sent to Google Sheets or stored; refreshing this page clears it.</p><Button onClick={() => { setSubmitted(false); setErrors({}); }} className="lime-cta">Write another review</Button></div>;
  return <form className="pp-review-form" noValidate onSubmit={handleSubmit} aria-busy={isSubmitting}><div className="pp-review-form-grid"><label className="pp-form-field"><span>Your name *</span><Input name="reviewerName" aria-invalid={Boolean(errors.name)} placeholder="Your name" disabled={isSubmitting} />{errors.name && <small>{errors.name}</small>}</label><label className="pp-form-field"><span>Email address *</span><Input name="reviewerEmail" type="email" aria-invalid={Boolean(errors.email)} placeholder="you@example.com" disabled={isSubmitting} />{errors.email && <small>{errors.email}</small>}</label></div><fieldset className="pp-review-rating" aria-describedby={errors.rating ? "review-rating-error" : undefined} disabled={isSubmitting}><legend>Your rating *</legend><div role="radiogroup" aria-label="Your rating">{[1, 2, 3, 4, 5].map((value) => <button type="button" key={value} className={value <= rating ? "is-selected" : ""} aria-pressed={value === rating} aria-label={`${value} out of 5 stars`} onClick={() => { setRating(value); setErrors((current) => { const next = { ...current }; delete next.rating; return next; }); }}><Star size={18} fill="currentColor" /></button>)}</div>{errors.rating && <small id="review-rating-error">{errors.rating}</small>}</fieldset><label className="pp-form-field"><span>Your review *</span><Textarea name="reviewFeedback" aria-invalid={Boolean(errors.feedback)} placeholder="What did you appreciate, or what could we improve?" disabled={isSubmitting} />{errors.feedback && <small>{errors.feedback}</small>}</label><div className="pp-review-submit"><label className="pp-consent"><input name="reviewConsent" type="checkbox" aria-invalid={Boolean(errors.consent)} disabled={isSubmitting} /><span>I understand this review is shown only in this browser session and clears on refresh. My email will not be displayed.</span></label>{errors.consent && <small>{errors.consent}</small>}<p>Send review to display it immediately in this page’s Reviews section.</p>{isSubmitting && <p className="pp-review-progress" role="status" aria-live="polite"><LoaderCircle size={16} className="pp-spinner" />Adding your review to this page…</p>}<Button type="submit" className="lime-cta" disabled={isSubmitting}>{isSubmitting ? <><LoaderCircle size={17} className="pp-spinner" />Showing review…</> : <><MessageCircleHeart size={17} />Send review</>}</Button></div></form>;
}
